// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxx3FZrCi5h9eVdhO_dhBPHCJekmdUlkA',
    appId: '1:620878918765:web:a9d260688895ae70fabb64',
    messagingSenderId: '620878918765',
    projectId: 'flutter-app-711a6',
    authDomain: 'flutter-app-711a6.firebaseapp.com',
    storageBucket: 'flutter-app-711a6.firebasestorage.app',
    measurementId: 'G-0KETLK4RN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1-6Eh_Ax0NxGbkdho54afKPMngVN7j0',
    appId: '1:620878918765:android:5fd21fcddb093e66fabb64',
    messagingSenderId: '620878918765',
    projectId: 'flutter-app-711a6',
    storageBucket: 'flutter-app-711a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxx3FZrCi5h9eVdhO_dhBPHCJekmdUlkA',
    appId: '1:620878918765:web:194e7c376e63e394fabb64',
    messagingSenderId: '620878918765',
    projectId: 'flutter-app-711a6',
    authDomain: 'flutter-app-711a6.firebaseapp.com',
    storageBucket: 'flutter-app-711a6.firebasestorage.app',
    measurementId: 'G-N7EHB3MSBQ',
  );
}
